# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a446561234d1ab882c726c0e4074f5726256f5b4d5bf8b631f81757d8e12e23eb046f81c7a6f2b12c6de651b8ba2788475b195631b02c063f6801f87dac219f2

test:
  secret_key_base: 2a1e30750639fe709fa10917df1f6a142c876653873d6bdb9efa505d60d60d83229469cf9ffdbc6644bab2044c589921f9b767f3710ce53db0393087d1b24609

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
